name: Build and deploy Node.js app to Azure Web App - IntanExplorer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install and build
        run: |
          npm install --production
          npm run build
      
      - name: Zip the application for deployment
        run: |
          zip -r release.zip dist node_modules package.json package-lock.json


      - name: Upload dist artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production  # Use lowercase here
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download dist artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip dist artifact for deployment and show contents
        run: |
          unzip release.zip -d ./deployment/
          ls -l ./deployment/
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IntanExplorer'
          slot-name: 'production'  # Use lowercase here
          package: ./deployment/  # Deploy the folder where we unzipped the content
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DA4C36A4C9A24A45B69EC510300651B1 }}
