name: Build and deploy Node.js app to Azure Web App - IntanExplorer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Zip the application for deployment
        run: |
          zip -r release.zip dist package.json package-lock.json

      - name: Upload dist artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production # Use lowercase here
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download dist artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip dist artifact for deployment and show contents
        run: |
          unzip release.zip -d ./deployment/
          ls -l ./deployment/

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'explorer-server-1'
          slot-name: 'production' # Use lowercase here
          package: ./deployment/ # Deploy the folder where we unzipped the content
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1685DC4F543D4CDB8589FCAFE63E9E28 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21D8356B1813483AB29F934F95396A35 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6D5CC5848684800B468B7D57794E80C }}
